### PR TITLE
Implemented dryRunMode

### PR DESCRIPTION
**Pull request by kanhaiya04**
## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any] #190 

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

### CODE REVIEW

**Review by DivergentEuropeans — CHANGES_REQUESTED** [review]
This is a great start! well done @kanhaiya04 it nearly all works for me

image

a) clicking this button leads to another UI that you missed. I'll send you a video in DMs

b) "APF" step after clicking Initialize APF Authorization, and I see green check marks, wait a few seconds, and it goes back to In progress arrows. This may not be related to your PR, but you should take a look if it is

**Review by DivergentEuropeans — COMMENTED** [review]
Almost.

"Upload Zowe PAX for offline install" install type doesn't lead to confirm button. You could do it after pressing "Upload Pax" button

**Comment by kanhaiya04** [comment]
@DivergentEuropeans Done

**Review by DivergentEuropeans — APPROVED** [review]
This now looks good

**Pull request merged**
